name: hello-world
on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  
      - name: my-step
        run: echo "My First AWS resources using GHE Actions"
      - name: Terraform init
        run: terraform init 
        working-directory: main
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply